// Generated by CoffeeScript 1.4.0
(function() {

  goog.require('gameOff');

  describe("Grid", function() {
    var grid;
    grid = 0;
    beforeEach(function() {
      return grid = new gameOff.Grid(10, 10);
    });
    it("should be created", function() {
      return expect(grid).toBeDefined();
    });
    return it("should have 10 rows", function() {
      return expect(grid.grid.length).toBe(10);
    });
  });

}).call(this);
